### PR TITLE
Hide on launch + only call isUserInteractingWithStatusBar if needed

### PR DESCRIPTION
**Pull request by aonez**
Added hide on launch option #29

---

I was wondering why the 0.3 constant CPU usage and turns out it's this 0.5 sec check:

https://github.com/Mortennn/Dozer/blob/67dabd3b12581af4d193a631acaf222deaa9e1f0/Dozer/DozerIcons.swift#L28-L32

So with this fix `isUserInteractingWithStatusBar` is only called if:

1. autohide option is enabled
2. the icons are visible

### CODE REVIEW

**Comment by aonez** [comment]
After a few minutes with Dozer running and untouched. Bottom version has this patch:
Screen Shot 2019-09-30 at 16 39 49

**Comment by Mortennn** [comment]
Looks great!

I will check it out within a few days.

**Comment by AndrewMast** [comment]
@aonez All of your changes look solid. Thank you for doing this! I hope it's merged soon.

**Comment by Mortennn** [comment]
Works great! Thank you🙌

**Comment by Mortennn** [comment]
I've released a prerelease with the changes [Dozer.4.1.0](https://github.com/Mortennn/Dozer/releases/tag/4.1.0).

**Comment by aonez** [comment]
Thanks @Mortennn!

**Pull request merged**
