### PR TITLE
changed status bar icons & spacing

### PR DESCRIPTION
**Pull request by petersf-libre**
includes extra unused arrow icons.

Screenshot of a possible configuration in use:
Screen Shot 2019-09-15 at 10 11 03 PM

### CODE REVIEW

**Comment by Mortennn** [comment]
Great!

I will check it out within the next week.

**Comment by aonez** [comment]
Can this be optional? I really like the dots.

**Comment by petersf-libre** [comment]
@aonez I really should have done that in the first place, I was just lazy. New commits have a (very) preliminary system for choosing icons

**Comment by aonez** [comment]
Maybe this pull can be used to fix #56?

**Comment by petersf-libre** [comment]
> Maybe this pull can be used to fix #56?

I actually just added that a bit ago, it has two sizes of dots as well as the arrows. It's up to @Mortennn which icons to keep and how to select them, though. Making the 'remove' icon dependent on the main icon would make the interface much cleaner but I wanted to make it easy to try out every option for now.

Screen Shot 2019-10-08 at 4 22 01 PM

This is the smaller dot it's using right now, but it's very easy to scale if people want something different.

**Comment by gqbre** [comment]
cool

**Comment by gingerbeardman** [comment]
Smaller dot does look better IMHO

**Comment by hjemmel** [comment]
Any updates on this?

**Comment by petersf-libre** [comment]
Closing as #101 is merged.

**Pull request closed without merging**
